In [1]:
import numpy as np
import copy, math

In [2]:
x_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])
print('x_train:',x_train)
print('y_train:',y_train)

x_train: [[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y_train: [460 232 178]


In [3]:
# data is stored in numpy array/matrix
print(f"X Shape: {x_train.shape}, X Type:{type(x_train)})")
print(x_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)

X Shape: (3, 4), X Type:<class 'numpy.ndarray'>)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y Shape: (3,), y Type:<class 'numpy.ndarray'>)
[460 232 178]


In [4]:
b_init = 785.1811367994083
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [7]:
def predict(x,w,b):
    #dpt product of w and b
    p=np.dot(x,w)+b
    return p

In [8]:
x_vec=x_train[0,:]
x_vec
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")
# make a prediction
f_wb = predict(x_vec,w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

x_vec shape (4,), x_vec value: [2104    5    1   45]
f_wb shape (), prediction: 459.9999976194083


In [ ]:
#function to calculate the overall cost
def compute_cost(X,y,w,b):
    m=X.shape[0]
    cost=0.0
    for i in range(m):
        f_wb_i=np.dot(X[i],w)+b
        cost+=((f_wb_i-y[i])**2)
    cost=cost/(2*m)
    return cost

In [14]:
cost = compute_cost(x_train, y_train, w_init, b_init)
print(f'Cost at optimal W :',{cost})

Cost at optimal W : {1.5578904428966628e-12}


In [50]:
def compute_gradient(X,y,w,b):

    m,n=X.shape
    print('m:',m)
    print('n:',n)
    #random initialisation of db and dW
    dj_db = 0.
    dj_dw=np.zeros((n,))

    for i in range(m):
        err = (np.dot(X[i],w)+b)-y[i]
        print(f'error{i}',err)
        for j in range(n):
            print( f'dj_dw{j}_before', dj_dw[j])
            dj_dw[j]=dj_dw[j]+err*X[i,j]
            print( f'dj_dw{j}_after', dj_dw[j])
            print(f'dj_dw{j}:',dj_dw[j])
        print( f'dj_db{i}_before',dj_db)
        dj_db +=err
        print( f'dj_db{i}_after',dj_db)
        print()
    dj_dw+=dj_dw/m
    dj_db+=dj_db/m
    print('dj_db',dj_db)
    print('dj_dw',dj_dw)

    return dj_dw,dj_db


In [51]:
tmp_dj_db, tmp_dj_dw = compute_gradient(x_train, y_train, w_init, b_init)

m: 3
n: 4
error0 -2.380591695327894e-06
dj_dw0_before 0.0
dj_dw0_after -0.005008764926969889
dj_dw0: -0.005008764926969889
dj_dw1_before 0.0
dj_dw1_after -1.190295847663947e-05
dj_dw1: -1.190295847663947e-05
dj_dw2_before 0.0
dj_dw2_after -2.380591695327894e-06
dj_dw2: -2.380591695327894e-06
dj_dw3_before 0.0
dj_dw3_after -0.00010712662628975522
dj_dw3: -0.00010712662628975522
dj_db0_before 0.0
dj_db0_after -2.380591695327894e-06

error1 -1.6305918961734278e-06
dj_dw0_before -0.005008764926969889
dj_dw0_after -0.007317683051951462
dj_dw0: -0.007317683051951462
dj_dw1_before -1.190295847663947e-05
dj_dw1_after -1.6794734165159753e-05
dj_dw1: -1.6794734165159753e-05
dj_dw2_before -2.380591695327894e-06
dj_dw2_after -5.6417754876747495e-06
dj_dw2: -5.6417754876747495e-06
dj_dw3_before -0.00010712662628975522
dj_dw3_after -0.00017235030213669233
dj_dw3: -0.00017235030213669233
dj_db1_before -2.380591695327894e-06
dj_db1_after -4.011183591501322e-06

error2 -1.0105918590852525e-06
dj_dw0_be

In [53]:
def compute_gradient(X, y, w, b): 
    m,n = X.shape           #(number of examples, number of features)
    dj_dw = np.zeros((n,))
   
    dj_db = 0.

    for i in range(m):                             
        err = (np.dot(X[i], w) + b) - y[i]   
        for j in range(n):                         
            dj_dw[j] = dj_dw[j] + err * X[i, j]    
        dj_db = dj_db + err                        
    dj_dw = dj_dw / m                                
    dj_db = dj_db / m                                
        
    return dj_db, dj_dw

In [54]:
#Compute and display gradient 
tmp_dj_db, tmp_dj_dw = compute_gradient(x_train, y_train, w_init, b_init)
print(f'dj_db at initial w,b: {tmp_dj_db}')
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')

dj_db at initial w,b: -1.6739251501955248e-06
dj_dw at initial w,b: 
 [-2.72623577e-03 -6.27197263e-06 -2.21745578e-06 -6.92403391e-05]


In [70]:
def gradient_descent(x,y,w_in,b_in,cost_function,gradient_function,alpha,num_iters):
    J_history = []
    w=copy.deepcopy(w_in)
    b=b_in

    for i in range(num_iters):
        dj_dw,dj_db=gradient_function(x,y,w,b)

        w=w-alpha*dj_dw
        b=b-alpha*dj_db

        if i < 100000:
            J_history.append(cost_function(x,y,w,b))

        if i%math.ceil(num_iters/10) == 0:
            print(f'Iteration {i:4d}: Cost {J_history[-1]:8.2f}')
    return w,b,J_history


In [71]:
x_train

array([[2104,    5,    1,   45],
       [1416,    3,    2,   40],
       [ 852,    2,    1,   35]])

In [72]:

initial_w = np.zeros_like(w_init)
initial_b = 0.
iterations = 1000
alpha = 5.0e-7
w_final, b_final, J_hist = gradient_descent(x_train, y_train,initial_w,initial_b,
                                                    compute_cost, compute_gradient, 
                                                    alpha, iterations)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
m,_ = x_train.shape
for i in range(m):
    print(f"prediction: {np.dot(x_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

TypeError: unsupported format string passed to numpy.ndarray.__format__